name: Documentation CI
on:
  pull_request:
    paths:
      - 'charts/documentation/**'
      - 'docs/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docs
        run: make docs
      - name: Lint Helm Chart
        run: helm lint charts/documentation